---
title: "Untitled"
author: "James Spalding"
date: "2023-12-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Data cleaning/creation

```{r}
roster09 = read.csv("reg_roster_2009.csv")  %>%
  filter(position == "QB")

roster10 = read.csv("reg_roster_2010.csv")  %>%
  filter(position == "QB")

roster11 = read.csv("reg_roster_2011.csv")  %>%
  filter(position == "QB")

roster12 = read.csv("reg_roster_2012.csv")  %>%
  filter(position == "QB")

roster13 = read.csv("reg_roster_2013.csv")  %>%
  filter(position == "QB")

roster14 = read.csv("reg_roster_2014.csv")  %>%
  filter(position == "QB")

roster15 = read.csv("reg_roster_2015.csv")  %>%
  filter(position == "QB")

roster16 = read.csv("reg_roster_2016.csv")  %>%
  filter(position == "QB")

roster17 = read.csv("reg_roster_2017.csv")  %>%
  filter(position == "QB")

roster18 = read.csv("reg_roster_2018.csv")  %>%
  filter(position == "QB")

roster19 = read.csv("reg_roster_2019.csv")  %>%
  filter(position == "QB")

qbsCombined = rbind(roster09, roster10, roster11, roster12, roster13, roster14, roster15, roster16, roster17, roster18, roster19) %>%
  select(-season_type)
```


```{r}
qb09 = read.csv("QBStats_2009.csv") %>%
  select(-lg) %>%
  group_by(qb) %>%
  summarize(att = sum(att),  cmp = sum(cmp), yds = sum(yds), ypa = sum(ypa), td = sum(td), int = sum(as.numeric(int)), sack = sum(sack), loss = sum(loss), game_points = sum(game_points)) %>%
  na.omit()
qb09$year = rep(2009, each = nrow(qb09)) #year column


qb10 = read.csv("QBStats_2010.csv") %>%
  select(-lg) %>%
  group_by(qb) %>%
  summarize(att = sum(att),  cmp = sum(cmp), yds = sum(yds), ypa = sum(ypa), td = sum(td), int = sum(as.numeric(int)), sack = sum(sack), loss = sum(loss), game_points = sum(game_points)) %>%
  na.omit()
qb10$year = rep(2010, each = nrow(qb10)) #year column


qb11 = read.csv("QBStats_2011.csv") %>%
  select(-lg) %>%
  group_by(qb) %>%
  summarize(att = sum(att),  cmp = sum(cmp), yds = sum(yds), ypa = sum(ypa), td = sum(td), int = sum(as.numeric(int)), sack = sum(sack), loss = sum(loss), game_points = sum(game_points)) %>%
  na.omit()
qb11$year = rep(2011, each = nrow(qb11)) #year column


qb12 = read.csv("QBStats_2012.csv") %>%
  select(-lg) %>%
  group_by(qb) %>%
  summarize(att = sum(att),  cmp = sum(cmp), yds = sum(yds), ypa = sum(ypa), td = sum(td), int = sum(as.numeric(int)), sack = sum(sack), loss = sum(loss), game_points = sum(game_points)) %>%
  na.omit()
qb12$year = rep(2012, each = nrow(qb12)) #year column


qb13 = read.csv("QBStats_2013.csv") %>%
  select(-lg) %>%
  group_by(qb) %>%
  summarize(att = sum(att),  cmp = sum(cmp), yds = sum(yds), ypa = sum(ypa), td = sum(td), int = sum(as.numeric(int)), sack = sum(sack), loss = sum(loss), game_points = sum(game_points)) %>%
  na.omit()
qb13$year = rep(2013, each = nrow(qb13)) #year column


qb14 = read.csv("QBStats_2014.csv") %>%
  select(-lg) %>%
  group_by(qb) %>%
  summarize(att = sum(att),  cmp = sum(cmp), yds = sum(yds), ypa = sum(ypa), td = sum(td), int = sum(as.numeric(int)), sack = sum(sack), loss = sum(loss), game_points = sum(game_points)) %>%
  na.omit()
qb14$year = rep(2014, each = nrow(qb14)) #year column


qb15 = read.csv("QBStats_2015.csv") %>%
  select(-lg) %>%
  group_by(qb) %>%
  summarize(att = sum(att),  cmp = sum(cmp), yds = sum(yds), ypa = sum(ypa), td = sum(td), int = sum(as.numeric(int)), sack = sum(sack), loss = sum(loss), game_points = sum(game_points)) %>%
  na.omit()
qb15$year = rep(2015, each = nrow(qb15)) #year column


qb16 = read.csv("QBStats_2016.csv") %>%
  select(-lg) %>%
  group_by(qb) %>%
  summarize(att = sum(att),  cmp = sum(cmp), yds = sum(yds), ypa = sum(ypa), td = sum(td), int = sum(as.numeric(int)), sack = sum(sack), loss = sum(loss), game_points = sum(game_points)) %>%
  na.omit()
qb16$year = rep(2016, each = nrow(qb16)) #year column


qbCombined = rbind(qb09, qb10, qb11, qb12, qb13, qb14, qb15, qb16)

#qbStats = write.csv(qbCombined, "/Users/jamesspalding/Desktop/qbStats.csv")
```


# Joining combine and qbdata

```{r}
#Make name format same
combine2000 = combine_qb2000
combine2000$`Player` = sub("-.*", "", combine2000$`Player`) #combine players

results = combine2000 %>%
  filter(combine2000$Player %in% qbCombined$qb)



qbCombined$qb = sub("[A-Z]\\..*", "", qbCombined$qb) #nfl players

qbTotal = qbCombined %>%
  select(-year) %>%
  group_by(qb) %>%
  summarize(att = sum(att),  cmp = sum(cmp), yds = sum(yds), ypa = sum(ypa), td = sum(td), int = sum(as.numeric(int)), sack = sum(sack), loss = sum(loss), game_points = sum(game_points)) %>%
  na.omit()

names(results)[names(results) == "Player"] <- "qb"

combineQBCombined = merge(qbTotal, results, by = "qb")

#write.csv(combineQBCombined, "/Users/jamesspalding/Desktop/totalCombinedQB.csv")
```

# joining qbstats and totalcombinedQB

```{r}


qbStats = read.csv("qbStats.csv")
totalCombinedQB = read.csv("totalCombinedQB.csv")

qbStatsSum = qbStats %>%
  select(-X, -ypa) %>%
  group_by(qb) %>%
  summarize(att = sum(att),  cmp = sum(cmp), yds = sum(yds), ypa = sum(yds)/sum(att), td = sum(td), int = sum(as.numeric(int)), sack = sum(sack), loss = sum(loss), game_points = sum(game_points), experience = max(experience)) %>%
  na.omit()

totalCombinedQB = totalCombinedQB %>%
  select(-X)

career_combineStats = merge(qbStatsSum, totalCombinedQB, by = "qb") %>%
  select(-12:-22)

names(career_combineStats)[names(career_combineStats) == "att.x"] = "att"
names(career_combineStats)[names(career_combineStats) == "cmp.x"] = "cmp"
names(career_combineStats)[names(career_combineStats) == "yds.x"] = "yds"
names(career_combineStats)[names(career_combineStats) == "ypa.x"] = "ypa"
names(career_combineStats)[names(career_combineStats) == "td.x"] = "td"
names(career_combineStats)[names(career_combineStats) == "int.x"] = "int"
names(career_combineStats)[names(career_combineStats) == "sack.x"] = "sack"
names(career_combineStats)[names(career_combineStats) == "loss.x"] = "loss"
names(career_combineStats)[names(career_combineStats) == "game_points.x"] = "game_points"



#write.csv(career_combineStats, "/Users/jamesspalding/Desktop/career_combinedStats.csv")
```
# Removing NA values

```{r}
colSums(is.na(career_combineStats))

for(i in 1:126){
if(is.na(career_combineStats$Round[i]) == T){
  career_combineStats$Round[i] = 8
}
} #undrafted players

career_combineStats =  #removing bench because of large amount of NA
  career_combineStats %>%
  select(-BenchReps)

for(i in 1:126){ #removing player if they have more than 2 NA values (besides bench)
  if(sum(is.na(career_combineStats[i,]))>2){
    career_combineStats = career_combineStats[-i,]
  }
}

noncat = career_combineStats %>% #removing team and pick
  select(-Team, -Pick, -Pfr_ID)

noncat = noncat %>%
  mutate_all(~ ifelse(is.na(.), mean(., na.rm = TRUE), .))

colSums(is.na(noncat))

#write.csv(noncat, "/Users/jamesspalding/Desktop/career_combineNoNA.csv") #No NA values

<<<<<<< HEAD

=======
>>>>>>> 1e01a8dd90bd9b939ce35dbe3731d6c8128864a5
#year averages csv
noncat2 = noncat %>%
  mutate(experience = experience + 1, #0th year is now 1st year
         att = att/experience,
         cmp = cmp/experience,
         yds = yds/experience,
         td = td/experience,
         int = int/experience,
         sack = sack/experience,
         loss = loss/experience,
         game_points = game_points/experience
         )

for(i in 1:103){
  if(is.infinite(rowSums(noncat2[,2:21])) == T){
    noncat2[i,] = noncat[i,]
  }
  if(is.nan(rowSums(noncat2[,2:21])) == T){
    noncat2[i,] = noncat[i,]
  }
}


#write.csv(noncat2, "/Users/jamesspalding/Desktop/career_combineNoNA_avgs.csv")
```

<<<<<<< HEAD
# Principal Component Visualization
=======
>>>>>>> 1e01a8dd90bd9b939ce35dbe3731d6c8128864a5

```{r}
# Princomp
library(ggfortify)
footballPC = princomp(noncat2[,2:21], cor = T)
summary(footballPC, loadings = T) #.61 with 2 comps

autoplot(footballPC, loadings=T, loadings.label=T, data = noncat2)

# Dimension Rediction
library(psych)
cortest.bartlett(cor(noncat2[,2:21]), n=103) #0 pval
KMO(cor(noncat2[,2:21])) #Overall .82

fa.out = principal(noncat2[,2:21],nfactors=2,rotate="varimax")
print.psych(fa.out,cut=.5,sort=TRUE) #No cross-loading!

# fa.out = principal(noncat2[,2:21],nfactors=2,rotate="promax")
# print.psych(fa.out,cut=.5,sort=TRUE) #Both return same groups

# 2 distinct groupings, game stats and physical stats


#Group 1 pca (game stats)
  group1 = noncat2 %>%
    select(att, yds, cmp, game_points, td, sack, loss, int, AV, Round)
  
  
  g1PC = princomp(group1, cor = T)
  #summary(g1PC, loadings = T) #.92 with 2 comps
  
  autoplot(g1PC, loadings=T, loadings.label=T, data = group1)


#Group 2 pca (physical attributes)
  group2 = noncat2 %>%
    select(Forty, Vertical, BroadJump, Shuttle, Cone)
  
  
  g2PC = princomp(group2, cor = T)
  #summary(g2PC, loadings = T) #.81 with 2 comps
  
  autoplot(g2PC, loadings=T, loadings.label=T, data = group2) 
```













