---
title: "Push Test"
author: "Noah Coleman"
date: "2023-11-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(MASS)
library(ggplot2)
library(stringr)
library(rvest)
library(devtools)
library(stringr)

```


```{r}
#Combine Datasets

# combine <- read_csv("nfl.combine.csv")
# combine.rnd <- str_split_fixed(combine$Drafted..tm.rnd.yr.,'/',4)
# combine1 <- bind_cols(combine,combine.rnd)
# combine2 <- combine1[,-c(13,16,22)]
# 
# 
# names(combine2) <- c("Year Drafted", "Player Name", "Age", "School", "Height", "Weight", "40 Yd Dash", "Vertical Jump", " Bench Press(Reps)", "Broad Jump", "3 Cone Agility", "20 Yd Shuttle", "BMI", "Player Type", "Position", "Drafted", "Team", "Round Drafted","Pick Number")
# attach(combine2)
# filter.qb <- combine2 %>% filter(Position == "QB")
# write.csv(filter.qb,file = "combine.qb")
#Unused combine data; doesn't have the right years for us to use


combine.full <- read.csv("combine.2000.2018.csv")
combine.qb <- combine.full %>% filter(Pos== "QB")
write.csv(combine.qb, file = "combine.qb2000.csv")
```
```{r}
qb.data <- read.csv("qbStats.csv")

```

```{r}
#Years Pro dataset
link <- "https://www.pro-football-reference.com/players/qbindex.htm"
link.read <- read_html(link)
nodes <- html_nodes(link.read, "table")
link.table <- html_table(nodes, fill=TRUE)
years.pro.raw <-as.data.frame(link.table)
years.pro <- years.pro.raw %>% mutate(YearsPro = To - From)
years.pro2 <- years.pro[,-3]
years.pro3 <- years.pro2 %>% filter(From >= 1996)
years.pro3 <- years.pro3 %>% filter(From <= 2016)
names(years.pro3) <- c("qb","Position", "From","To","YearsPro")

```

```{r}
#Passing stats by season
qb.stats <- read.csv("qbStats.csv")

#combine.stats.09.16<- read.csv("totalCombinedQB.csv") commented out as its no longer in use

#combine years pro with this; Total stats from 2009-2016; complete dataset
qb.almost <- read.csv("career_combinedStats.csv")
qb.total <- qb.almost[,-c(1,17,22,23)]
summary(qb.total)

#Label UDFA as round 8
round.nas <- which(is.na(qb.total$Round))
qb.total$Round[round.nas] <- 8
#Create more stats that account for number of attempts
qb.total <- qb.total %>% mutate(tdper = td/att)

#completion percentage
qb.total <- qb.total %>% mutate(cmppct = cmp/att)

#int per attempts
qb.total <- qb.total %>% mutate(intper = int/att)

qb.total <- qb.total %>% mutate(sackper = sack/att)

qb.total <- qb.total %>% mutate(lossper = loss/sack)

```


```{r}
library(psych)
#Multiple Regression Investigation
numerical.qb <- qb.total %>% dplyr::select(c(att, cmp, yds, int, ypa, td, int, sack, loss, game_points, experience, Ht, Wt, Year,tdper, cmppct,intper,sackper,lossper, Round))


mod1 <- lm(cbind(experience,ypa,tdper,cmppct,intper)~ Ht + Wt + Forty + Round + Vertical, data = qb.total )
summary(mod1)
#create correlation matrix
mat <- cor(numerical.qb)
#Cortest-Bartlett Test
cortest.bartlett(mat, n=length(numerical.qb))
mat

#Create dataset with only over 30 attempts, at least 1 full game played
qb.play <- numerical.qb[numerical.qb$att >29,]
mat2 <- cor(qb.play)
cortest.bartlett(mat2, n=length(qb.play))
mat2

```


